# Generated by Django 4.2.15 on 2024-09-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_token_created_on_token_modified_on_user_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'default_related_name': 'related_user_token'},
        ),
    ]
